"""
Generate shared slot config for backend, frontend, and Arduino from spice_slots.json.

Run from repo root: python generate_slots.py
"""

import json
import sys
import os
import argparse
import sqlite3


CONFIG_FILE = os.path.join(os.path.dirname(__file__), "spice_slots.json")

PYTHON_OUT = os.path.join(
    os.path.dirname(__file__), "bland2grand-backend", "slot_config.py"
)
TS_OUT = os.path.join(
    os.path.dirname(__file__), "bland2grand-frontend", "src", "slotConfig.ts"
)
ARDUINO_OUT = os.path.join(
    os.path.dirname(__file__), "Bland2Grand_Arduino", "src", "SlotConfig.h"
)

# helpers 

def load_config():
    with open(CONFIG_FILE) as f:
        data = json.load(f)
    # Normalise: keys as ints, guaranteed sorted 1-8
    slots = {}
    for k, v in data["slots"].items():
        slots[int(k)] = v
    assert list(slots.keys()) == list(range(1, 9)), "slots must be exactly 1-8"
    return slots


def col_name(slot: int, name: str) -> str:
    """Derive the SQL column name for a slot, e.g. s3_garlic_powder"""
    slug = name.lower().replace(" ", "_").replace("-", "_")
    return f"s{slot}_{slug}"


# generators 

def gen_python(slots: dict) -> str:
    lines = [
        "# AUTO-GENERATED by generate_slots.py -- do not edit by hand.",
        "# Edit spice_slots.json and re-run generate_slots.py.",
        "",
        "SPICE_SLOTS: dict[int, str] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: "{info["name"]}",')
    lines += [
        "}",
        "",
        "SPICE_DENSITY_G_PER_ML: dict[int, float] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: {info["density_g_ml"]},  # {info["name"]}')
    lines += [
        "}",
        "",
        "SPICE_COLORS: dict[int, str] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: "{info["color"]}",  # {info["name"]}')
    lines += [
        "}",
        "",
        "# SQL column name for each slot (used by database.py)",
        "SLOT_COLUMNS: dict[int, str] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: "{col_name(slot, info["name"])}",')
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_typescript(slots: dict) -> str:
    lines = [
        "// AUTO-GENERATED by generate_slots.py -- do not edit by hand.",
        "// Edit spice_slots.json and re-run generate_slots.py.",
        "",
        "export const SPICE_SLOTS: Record<number, string> = {",
    ]
    for slot, info in slots.items():
        lines.append(f'  {slot}: "{info["name"]}",')
    lines += [
        "};",
        "",
        "export const SPICE_COLORS: Record<number, string> = {",
    ]
    for slot, info in slots.items():
        lines.append(f'  {slot}: "{info["color"]}",  // {info["name"]}')
    lines += [
        "};",
        "",
        "export const SPICE_DENSITY_G_PER_ML: Record<number, number> = {",
    ]
    for slot, info in slots.items():
        lines.append(f'  {slot}: {info["density_g_ml"]},  // {info["name"]}')
    lines += [
        "};",
        "",
        "// Re-export as SPICE_LABELS for components that use that name",
        "export const SPICE_LABELS = SPICE_SLOTS;",
    ]
    return "\n".join(lines) + "\n"


def gen_arduino(slots: dict) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_slots.py -- do not edit by hand.",
        "// Edit spice_slots.json and re-run generate_slots.py.",
        "",
        '#include "Constants.h"',
        "",
        "// Slot names (for Serial debug output)",
        "static const char* const SPICE_NAMES[CAROUSEL_SLOT_COUNT + 1] = {",
        '    "",  // index 0 unused',
    ]
    for slot, info in slots.items():
        lines.append(f'    "{info["name"]}",  // slot {slot}')
    lines += [
        "};",
        "",
        "// Grams dispensed per auger revolution, indexed 0..CAROUSEL_SLOT_COUNT",
        "// index 0 is unused (slots are 1-based)",
        "static constexpr float GRAMS_PER_REV[CAROUSEL_SLOT_COUNT + 1] = {",
        "    0.0f,  // index 0 -- unused",
    ]

    for slot, info in slots.items():
        lines.append(f'    {info["grams_per_rev"]}f,  // slot {slot} -- {info["name"]}')
    lines.append("};")
    return "\n".join(lines) + "\n"


# database migration
def migrate_db(db_path: str, slots: dict):
    if not os.path.exists(db_path):
        print(f"[DB] {db_path} not found -- skipping.")
        return

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # Always check for leftover recipes_backup and merge missing rows first
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='recipes_backup'")
    if cur.fetchone():
        cur.execute("SELECT COUNT(*) FROM recipes_backup")
        backup_count = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM recipes")
        live_count = cur.fetchone()[0]
        print(f"[DB] Found recipes_backup ({backup_count} rows) vs live ({live_count} rows).")

        # Get backup columns and live columns
        cur.execute("PRAGMA table_info(recipes_backup)")
        backup_cols = [row[1] for row in cur.fetchall()]
        cur.execute("PRAGMA table_info(recipes)")
        live_cols = [row[1] for row in cur.fetchall()]

        backup_slot_cols = {
            int(c[1]): c for c in backup_cols
            if len(c) >= 3 and c[0] == 's' and c[1].isdigit() and c[2] == '_'
        }
        live_slot_cols = {
            int(c[1]): c for c in live_cols
            if len(c) >= 3 and c[0] == 's' and c[1].isdigit() and c[2] == '_'
        }

        # Fetch rows in backup that are missing from live
        cur.execute("""
            SELECT * FROM recipes_backup
            WHERE name NOT IN (SELECT name FROM recipes)
        """)
        missing_rows = cur.fetchall()
        backup_idx = {col: i for i, col in enumerate(backup_cols)}

        if missing_rows:
            print(f"[DB] Copying {len(missing_rows)} missing recipes from backup...")
            non_slot = ['name', 'category', 'description']
            live_slot_col_list = [live_slot_cols[s] for s in sorted(live_slot_cols.keys())]
            col_list = ', '.join(non_slot + live_slot_col_list)
            placeholders = ', '.join(['?'] * (len(non_slot) + len(live_slot_col_list)))
            insert_sql = f"INSERT OR IGNORE INTO recipes ({col_list}) VALUES ({placeholders})"

            for row in missing_rows:
                name        = row[backup_idx['name']]
                category    = row[backup_idx.get('category', -1)] if 'category' in backup_idx else 'General'
                description = row[backup_idx.get('description', -1)] if 'description' in backup_idx else ''
                slot_values = []
                for slot_num in sorted(live_slot_cols.keys()):
                    old_col = backup_slot_cols.get(slot_num)
                    if old_col and old_col in backup_idx:
                        slot_values.append(row[backup_idx[old_col]])
                    else:
                        slot_values.append(0.0)
                cur.execute(insert_sql, [name, category, description] + slot_values)
                print(f"  + {name}")

            conn.commit()
            print(f"[DB] Done merging backup recipes.")

        print("[DB] Dropping recipes_backup.")
        cur.execute("DROP TABLE recipes_backup")
        conn.commit()

    # Read existing schema
    cur.execute("PRAGMA table_info(recipes)")
    existing_cols = [row[1] for row in cur.fetchall()]
    existing_set = set(existing_cols)

    new_col_for = {slot: col_name(slot, info["name"]) for slot, info in slots.items()}
    desired_set = set(new_col_for.values())

    if desired_set.issubset(existing_set):
        print("[DB] Column names already match config -- no migration needed.")
        conn.close()
        return

    print("[DB] Column mismatch detected. Migrating recipes table...")

    new_name_to_slot = {info["name"]: slot for slot, info in slots.items()}

    # Build old column name -> spice name mapping
    old_col_to_name: dict[str, str] = {}
    for col in existing_cols:
        if len(col) >= 3 and col[0] == "s" and col[1].isdigit() and col[2] == "_":
            # extract spice slug from old col e.g. s1_salt -> salt
            slug = "_".join(col.split("_")[1:])
            # match to a current spice name by slug
            for slot, info in slots.items():
                if info["name"].lower().replace(" ", "_") == slug:
                    old_col_to_name[col] = info["name"]
                    break

    # old_col_for now maps new slot -> old column where that spice's data lives
    old_col_for: dict[int, str | None] = {s: None for s in slots}
    for old_col, spice_name in old_col_to_name.items():
        new_slot = new_name_to_slot.get(spice_name)
        if new_slot is not None:
            old_col_for[new_slot] = old_col

    print("  Slot mapping (old column -> new column):")
    for s in slots:
        old = old_col_for[s] or "(none → 0)"
        print(f"    slot {s}: {old:30s} -> {new_col_for[s]}")

    non_slot_cols = [
        c for c in existing_cols
        if not (len(c) >= 3 and c[0] == "s" and c[1].isdigit() and c[2] == "_")
    ]

    new_col_defs = [f"{new_col_for[s]} REAL DEFAULT 0" for s in slots]

    cur.execute("SELECT * FROM recipes")
    all_rows = cur.fetchall()
    col_index = {col: i for i, col in enumerate(existing_cols)}
    print(f"[DB] Preserving {len(all_rows)} existing recipes.")

    cur.execute("ALTER TABLE recipes RENAME TO _recipes_backup")
    cur.execute(f"""
        CREATE TABLE recipes (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            name        TEXT NOT NULL UNIQUE,
            category    TEXT DEFAULT 'General',
            description TEXT DEFAULT '',
            {', '.join(new_col_defs)}
        )
    """)

    insert_cols = non_slot_cols + [new_col_for[s] for s in slots]
    placeholders = ", ".join(["?"] * len(insert_cols))
    insert_sql = f"INSERT INTO recipes ({', '.join(insert_cols)}) VALUES ({placeholders})"

    rows_copied = 0
    for row in all_rows:
        values = []
        for c in non_slot_cols:
            values.append(row[col_index[c]] if c in col_index else None)
        for s in slots:
            old_col = old_col_for[s]
            if old_col and old_col in col_index:
                values.append(row[col_index[old_col]])
            else:
                values.append(0.0)
        cur.execute(insert_sql, values)
        rows_copied += 1

    cur.execute("DROP TABLE _recipes_backup")

    for slot, info in slots.items():
        cur.execute(
            "INSERT INTO calibration (slot, spice_name, cal_factor) VALUES (?, ?, 1000.0) "
            "ON CONFLICT(slot) DO UPDATE SET spice_name = excluded.spice_name",
            (slot, info["name"]),
        )

    conn.commit()
    print(f"[DB] Migration complete. {rows_copied} recipes preserved.")
    conn.close()

# seed file patch 

def patch_seed_file(slots: dict):
    """
    Updates the SPICE_SLOTS import in seed_recipes.py to use slot_config.py.
    Also prints a reminder about updating seed recipe gram values.
    """
    print("\n[SEED] Reminder: if you moved spices between physical slots,")
    print("       update the gram values in bland2grand-backend/seed_recipes.py")
    print("       so recipes still dispense from the correct new slot numbers.")
    print("       The slot->name mapping is now auto-managed via slot_config.py.")


# main 

def write(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"[OK] Written: {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--db",
        default="bland2grand-backend/bland2grand.db",
        help="Path to SQLite database (for column migration)",
    )
    parser.add_argument(
        "--skip-db", action="store_true", help="Skip database migration"
    )
    args = parser.parse_args()

    print(f"Loading {CONFIG_FILE}…")
    slots = load_config()

    print("\nSlot configuration:")
    for slot, info in slots.items():
        print(
            f"{slot}: {info['name']:<16}  {info['grams_per_rev']} g/rev  density {info['density_g_ml']} g/mL"
        )
        
    write(PYTHON_OUT, gen_python(slots))
    write(TS_OUT, gen_typescript(slots))
    write(ARDUINO_OUT, gen_arduino(slots))

    if not args.skip_db:
        migrate_db(args.db, slots)

    patch_seed_file(slots)

    print("\nDone! Next steps:")
    print("1. Re-flash Arduino: pio run --target upload")
    print("2. Restart Flask: python app.py")
    print("3. Restart frontend: npm run dev  (or it hot-reloads)")
    print("4. Re-seed DB if needed: python seed_recipes.py")

if __name__ == "__main__":
    main()
