#!/usr/bin/env python3
"""
generate_slots.py
-----------------
Single source of truth: spice_slots.json
Run this after editing spice_slots.json to regenerate:
  - bland2grand-backend/slot_config.py       (Python config)
  - bland2grand-frontend/src/slotConfig.ts    (TypeScript config)
  - Bland2Grand_Arduino/src/SlotConfig.h      (Arduino header)
  - Migrates the SQLite database to rename columns if needed

Usage:
    python generate_slots.py [--db path/to/bland2grand.db]
"""

import json
import sys
import os
import argparse
import sqlite3

CONFIG_FILE = os.path.join(os.path.dirname(__file__), "spice_slots.json")

PYTHON_OUT  = os.path.join(os.path.dirname(__file__), "bland2grand-backend", "slot_config.py")
TS_OUT      = os.path.join(os.path.dirname(__file__), "bland2grand-frontend", "src", "slotConfig.ts")
ARDUINO_OUT = os.path.join(os.path.dirname(__file__), "Bland2Grand_Arduino", "src", "SlotConfig.h")

# ── helpers ──────────────────────────────────────────────────────────────────

def load_config():
    with open(CONFIG_FILE) as f:
        data = json.load(f)
    # Normalise: keys as ints, guaranteed sorted 1-8
    slots = {}
    for k, v in data["slots"].items():
        slots[int(k)] = v
    assert list(slots.keys()) == list(range(1, 9)), "slots must be exactly 1-8"
    return slots

def col_name(slot: int, name: str) -> str:
    """Derive the SQL column name for a slot, e.g. s3_garlic_powder"""
    slug = name.lower().replace(" ", "_").replace("-", "_")
    return f"s{slot}_{slug}"

# ── generators ───────────────────────────────────────────────────────────────

def gen_python(slots: dict) -> str:
    lines = [
        "# AUTO-GENERATED by generate_slots.py — do not edit by hand.",
        "# Edit spice_slots.json and re-run generate_slots.py.",
        "",
        "SPICE_SLOTS: dict[int, str] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: "{info["name"]}",')
    lines += [
        "}",
        "",
        "SPICE_DENSITY_G_PER_ML: dict[int, float] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: {info["density_g_ml"]},  # {info["name"]}')
    lines += [
        "}",
        "",
        "SPICE_COLORS: dict[int, str] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: "{info["color"]}",  # {info["name"]}')
    lines += [
        "}",
        "",
        "# SQL column name for each slot (used by database.py)",
        "SLOT_COLUMNS: dict[int, str] = {",
    ]
    for slot, info in slots.items():
        lines.append(f'    {slot}: "{col_name(slot, info["name"])}",')
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_typescript(slots: dict) -> str:
    lines = [
        "// AUTO-GENERATED by generate_slots.py — do not edit by hand.",
        "// Edit spice_slots.json and re-run generate_slots.py.",
        "",
        "export const SPICE_SLOTS: Record<number, string> = {",
    ]
    for slot, info in slots.items():
        lines.append(f'  {slot}: "{info["name"]}",')
    lines += [
        "};",
        "",
        "export const SPICE_COLORS: Record<number, string> = {",
    ]
    for slot, info in slots.items():
        lines.append(f'  {slot}: "{info["color"]}",  // {info["name"]}')
    lines += [
        "};",
        "",
        "export const SPICE_DENSITY_G_PER_ML: Record<number, number> = {",
    ]
    for slot, info in slots.items():
        lines.append(f'  {slot}: {info["density_g_ml"]},  // {info["name"]}')
    lines += [
        "};",
        "",
        "// Re-export as SPICE_LABELS for components that use that name",
        "export const SPICE_LABELS = SPICE_SLOTS;",
    ]
    return "\n".join(lines) + "\n"


def gen_arduino(slots: dict) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_slots.py — do not edit by hand.",
        "// Edit spice_slots.json and re-run generate_slots.py.",
        "",
        '#include "Constants.h"',
        "",
        "// Slot names (for Serial debug output)",
        "static const char* const SPICE_NAMES[CAROUSEL_SLOT_COUNT + 1] = {",
        '    "",  // index 0 unused',
    ]
    for slot, info in slots.items():
        lines.append(f'    "{info["name"]}",  // slot {slot}')
    lines += [
        "};",
        "",
        "// Grams dispensed per auger revolution, indexed 0..CAROUSEL_SLOT_COUNT",
        "// index 0 is unused (slots are 1-based)",
        "static constexpr float GRAMS_PER_REV[CAROUSEL_SLOT_COUNT + 1] = {",
        "    0.0f,  // index 0 — unused",
    ]
    for slot, info in slots.items():
        lines.append(f'    {info["grams_per_rev"]}f,  // slot {slot} — {info["name"]}')
    lines.append("};")
    return "\n".join(lines) + "\n"


# ── database migration ────────────────────────────────────────────────────────

def migrate_db(db_path: str, slots: dict):
    """
    Migrates the recipes table so its spice columns match the config.

    Strategy (safe for all SQLite versions):
      1. Read existing columns via PRAGMA.
      2. If columns already match, do nothing.
      3. Otherwise:
         a. Rename old table to _backup.
         b. Create new table with correct column names.
         c. Copy each row, mapping old slot-n column -> new slot-n column
            by slot NUMBER (so data follows the physical slot, not the name).
            Any slot that had no column in the old schema gets 0.
         d. Drop backup, update calibration names.
    """
    if not os.path.exists(db_path):
        print(f"[DB] {db_path} not found — skipping (will be created fresh on next run).")
        return

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # ── read existing schema ──────────────────────────────────────────────────
    cur.execute("PRAGMA table_info(recipes)")
    existing_cols = [row[1] for row in cur.fetchall()]  # ordered list of column names
    existing_set  = set(existing_cols)

    # Desired new column name for each slot
    new_col_for = {slot: col_name(slot, info["name"]) for slot, info in slots.items()}
    new_col_defs = [f"{new_col_for[s]} REAL DEFAULT 0" for s in slots]

    desired_set = set(new_col_for.values())

    if desired_set.issubset(existing_set) and len(desired_set) == 8:
        print("[DB] Column names already match config — no migration needed.")
        conn.close()
        return

    print("[DB] Column mismatch detected. Migrating recipes table…")

    # ── find old slot column for each slot number ─────────────────────────────
    # Pattern: s<digit>_<anything>  e.g. s4_chili_powder -> slot 4
    old_col_for: dict[int, str | None] = {s: None for s in slots}
    for col in existing_cols:
        if len(col) >= 3 and col[0] == "s" and col[1].isdigit() and col[2] == "_":
            try:
                slot_num = int(col[1])
                if slot_num in old_col_for:
                    old_col_for[slot_num] = col
            except ValueError:
                pass

    print("  Slot mapping (old column -> new column):")
    for s in slots:
        old = old_col_for[s] or "(none → 0)"
        print(f"    slot {s}: {old:30s} -> {new_col_for[s]}")

    # ── non-slot columns (id, name, category, description, …) ────────────────
    non_slot_cols = [
        c for c in existing_cols
        if not (len(c) >= 3 and c[0] == "s" and c[1].isdigit() and c[2] == "_")
    ]

    # ── create new table ──────────────────────────────────────────────────────
    cur.execute("ALTER TABLE recipes RENAME TO _recipes_backup")

    cur.execute(f"""
        CREATE TABLE recipes (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            name        TEXT NOT NULL UNIQUE,
            category    TEXT DEFAULT 'General',
            description TEXT DEFAULT '',
            {', '.join(new_col_defs)}
        )
    """)

    # ── copy data row by row (safe: no dynamic column list in SELECT) ─────────
    cur.execute(f"SELECT * FROM _recipes_backup")
    backup_cols = [d[0] for d in cur.description]
    backup_idx  = {c: i for i, c in enumerate(backup_cols)}

    insert_cols = non_slot_cols + [new_col_for[s] for s in slots]
    placeholders = ", ".join(["?"] * len(insert_cols))
    insert_sql = f"INSERT INTO recipes ({', '.join(insert_cols)}) VALUES ({placeholders})"

    rows_copied = 0
    for row in cur.fetchall():
        values = []
        # Non-slot columns: copy directly if they exist, else NULL
        for c in non_slot_cols:
            values.append(row[backup_idx[c]] if c in backup_idx else None)
        # Slot columns: use old column value if it existed, else 0
        for s in slots:
            old_col = old_col_for[s]
            if old_col and old_col in backup_idx:
                values.append(row[backup_idx[old_col]])
            else:
                values.append(0.0)
        cur.execute(insert_sql, values)
        rows_copied += 1

    cur.execute("DROP TABLE _recipes_backup")

    # ── update calibration table ──────────────────────────────────────────────
    for slot, info in slots.items():
        cur.execute(
            "INSERT INTO calibration (slot, spice_name, cal_factor) VALUES (?, ?, 1000.0) "
            "ON CONFLICT(slot) DO UPDATE SET spice_name = excluded.spice_name",
            (slot, info["name"])
        )

    conn.commit()
    print(f"[DB] Migration complete. {rows_copied} recipes preserved.")
    conn.close()


# ── seed file patch ───────────────────────────────────────────────────────────

def patch_seed_file(slots: dict):
    """
    Updates the SPICE_SLOTS import in seed_recipes.py to use slot_config.py.
    Also prints a reminder about updating seed recipe gram values.
    """
    print("\n[SEED] Reminder: if you moved spices between physical slots,")
    print("       update the gram values in bland2grand-backend/seed_recipes.py")
    print("       so recipes still dispense from the correct new slot numbers.")
    print("       The slot->name mapping is now auto-managed via slot_config.py.")


# ── main ─────────────────────────────────────────────────────────────────────

def write(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"[OK] Written: {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default="bland2grand-backend/bland2grand.db",
                        help="Path to SQLite database (for column migration)")
    parser.add_argument("--skip-db", action="store_true",
                        help="Skip database migration")
    args = parser.parse_args()

    print(f"Loading {CONFIG_FILE}…")
    slots = load_config()

    print("\nSlot configuration:")
    for slot, info in slots.items():
        print(f"  {slot}: {info['name']:<16}  {info['grams_per_rev']} g/rev  density {info['density_g_ml']} g/mL")

    print()
    write(PYTHON_OUT,  gen_python(slots))
    write(TS_OUT,      gen_typescript(slots))
    write(ARDUINO_OUT, gen_arduino(slots))

    if not args.skip_db:
        migrate_db(args.db, slots)

    patch_seed_file(slots)

    print("\nDone! Next steps:")
    print("  1. Re-flash Arduino:  pio run --target upload")
    print("  2. Restart Flask:     python app.py")
    print("  3. Restart frontend:  npm run dev  (or it hot-reloads)")
    print("  4. Re-seed DB if needed: python seed_recipes.py")


if __name__ == "__main__":
    main()