#pragma once
// AUTO-GENERATED by generate_slots.py -- do not edit by hand.
// Edit spice_slots.json and re-run generate_slots.py.

#include "Constants.h"

// Slot names (for Serial debug output)
static const char* const SPICE_NAMES[CAROUSEL_SLOT_COUNT + 1] = {
    "",  // index 0 unused
    "Salt",  // slot 1
    "Cumin",  // slot 2
    "Paprika",  // slot 3
    "Onion Powder",  // slot 4
    "Garlic Powder",  // slot 5
    "Black Pepper",  // slot 6
    "Oregano",  // slot 7
    "Cayenne",  // slot 8
};

// Grams dispensed per auger revolution, indexed 0..CAROUSEL_SLOT_COUNT
// index 0 is unused (slots are 1-based)
static constexpr float GRAMS_PER_REV[CAROUSEL_SLOT_COUNT + 1] = {
    0.0f,  // index 0 -- unused
    1.5f,  // slot 1 -- Salt
    0.75f,  // slot 2 -- Cumin
    0.65f,  // slot 3 -- Paprika
    0.75f,  // slot 4 -- Onion Powder
    0.8f,  // slot 5 -- Garlic Powder
    0.8f,  // slot 6 -- Black Pepper
    0.35f,  // slot 7 -- Oregano
    0.65f,  // slot 8 -- Cayenne
};
