[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

lib_deps = 
    waspinator/AccelStepper@^1.64
    bogde/HX711@^0.7.5
    robtillaart/AS5600@^0.6.7
    bblanchon/ArduinoJson@^7.2.2
    jandrassy/ArduinoOTA@^1.1.1