// AUTO-GENERATED by generate_slots.py -- do not edit by hand.
// Edit spice_slots.json and re-run generate_slots.py.

export const SPICE_SLOTS: Record<number, string> = {
  1: "Salt",
  2: "Black Pepper",
  3: "Onion Powder",
  4: "Garlic Powder",
  5: "Cumin",
  6: "Paprika",
  7: "Oregano",
  8: "Cayenne",
};

export const SPICE_COLORS: Record<number, string> = {
  1: "#E8EEF2",  // Salt
  2: "#6f009a",  // Black Pepper
  3: "#D4A870",  // Onion Powder
  4: "#D4C57A",  // Garlic Powder
  5: "#8B6914",  // Cumin
  6: "#C94020",  // Paprika
  7: "#4E7C55",  // Oregano
  8: "#C63B0A",  // Cayenne
};

export const SPICE_DENSITY_G_PER_ML: Record<number, number> = {
  1: 1.2,  // Salt
  2: 0.6,  // Black Pepper
  3: 0.5,  // Onion Powder
  4: 0.55,  // Garlic Powder
  5: 0.5,  // Cumin
  6: 0.45,  // Paprika
  7: 0.3,  // Oregano
  8: 0.45,  // Cayenne
};

// Re-export as SPICE_LABELS for components that use that name
export const SPICE_LABELS = SPICE_SLOTS;
